#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker358"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "21b502cbec2a429295b2bebc9bd343e5" }
]

[assets]
directory = "./public"
